spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:postgresql://localhost:5432/public
    username: Postgres
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
    show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
